[build]
  base = "Client" 
  command = "npm run build"
  publish = "dist"  

[[redirects]]
  from = "/api/*" 
  to = "https://to-do-application-git-main-mujahidrajas-projects.vercel.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200